version: "3.8"
services:
  qrsvc:
    build: .
    image: adidsus/qrsvc:latest
    container_name: qrsvc
    restart: unless-stopped
    environment:
      - PORT=2138
      - BASIC_AUTH_USER=aaa3Dev
      # - BASIC_AUTH_PASS=secret (lepiej użyj .env, nie trzymaj haseł w repo)
    networks:
      - proxy

networks:
  proxy:
    external: true
