version: "3.8"
services:
  qrsvc:
    build: .
    container_name: qrsvc
    restart: unless-stopped
    environment:
      - PORT=2138
    ports:
      - "2138:2138"
    networks:
      - proxy

networks:
  proxy:
    external: true
